language: c
compiler: clang
env:
  global:
    - GIT_NAME="marvim"
    - GIT_EMAIL="marvim@users.noreply.github.com"
    # Encrypted environment variables, see
    # http://docs.travis-ci.com/user/encryption-keys/
    - secure: G13kwiQU0GY+/H9Zf+shujRr/RP2tVcf9u6cdT6t9GLl8YzNDWz1NDLA0Ykh/kkYht9Bw36diPFcNsHVCs8KwZJcEWS5L2b9g5Cv9VzU7RyQE1uc+oBn2tbDamYUjMkhRGtvrTdVdpjyoQr2mhx5rh7KmOz5VDahLti5cR9yEAU=
  matrix:
    - REPORT=doxygen
    - REPORT=clang-report
    - REPORT=translation-report
    - REPORT=vimpatch-report
    - REPORT=doc-index
script:
  - ./scripts/publish-docs.sh

